# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib: 'puppetlabs/stdlib'
    puppetdb: 'puppetlabs/puppetdb'
    inifile: 'puppetlabs/inifile'
    postgresql: 'puppetlabs/postgresql'
    apt: 'puppetlabs/apt'
    concat: 'puppetlabs/concat'
    firewall: 'puppetlabs/firewall'
    r10k: 'puppet/r10k'
    ruby: 'puppetlabs/ruby'
    gcc: 'puppetlabs/gcc'
    make: 'puppet/make'
    vcsrepo: 'puppetlabs/vcsrepo'
    git: 'puppetlabs/git'
    portage: 'gentoo/portage'
    epel: 'stahnma/epel'
    puppetserver_gem: 'puppetlabs/puppetserver_gem'
    systemd: 'camptocamp/systemd'
  symlinks:
    profile: "#{source_dir}/../profile"
