source ENV['GEM_SOURCE'] || 'https://rubygems.org'

def location_for(place_or_version, fake_version = nil)
  git_url_regex = %r{\A(?<url>(https?|git)[:@][^#]*)(#(?<branch>.*))?}
  file_url_regex = %r{\Afile:\/\/(?<path>.*)}

  if place_or_version && (git_url = place_or_version.match(git_url_regex))
    [fake_version, { git: git_url[:url], branch: git_url[:branch], require: false }].compact
  elsif place_or_version && (file_url = place_or_version.match(file_url_regex))
    ['>= 0', { path: File.expand_path(file_url[:path]), require: false }]
  else
    [place_or_version, { require: false }]
  end
end

group :development do
  gem "json", '= 2.21.1',                        require: false
  gem "racc", '~> 1.8.0',                        require: false if Gem::Requirement.create(['>= 2.7.0', '< 3.0.0']).satisfied_by?(Gem::Version.new(RUBY_VERSION.dup))
  gem "deep_merge", '~> 1.2.2',                  require: false
  gem "voxpupuli-test", '~> 14.0',               require: false
  gem "voxpupuli-rubocop", '~> 5.0',             require: false
  gem "dependency_checker", '~> 1.0.0',          require: false
  gem "pry", '~> 0.10',                          require: false
  gem "simplecov-console", '~> 0.9',             require: false
  gem "puppet-debugger", '~> 1.0',               require: false
  gem "rb-readline", '= 0.5.5',                  require: false, platforms: [:mswin, :mingw, :x64_mingw]
  gem "rexml", '>= 3.0.0', '< 3.4.5',            require: false
end
group :development, :release_prep do
  gem "openvox-strings", '~> 7.0',        require: false
  gem "puppet-blacksmith", '~> 9.0',      require: false
end
group :acceptance do
  gem "voxpupuli-acceptance", '~> 4.0', require: false
  gem "vagrant-wrapper",                require: false
end

openvox_version = ENV['OPENVOX_GEM_VERSION']
openfact_version = ENV['OPENFACT_GEM_VERSION']
hiera_version = ENV['HIERA_GEM_VERSION']

gems = {}

gems['openvox'] = location_for(openvox_version)

# If openfact or hiera versions have been specified via the environment
# variables

gems['openfact'] = location_for(openfact_version) if openfact_version
gems['hiera'] = location_for(hiera_version) if hiera_version

gems.each do |gem_name, gem_params|
  gem gem_name, *gem_params
end

# Evaluate Gemfile.local and ~/.gemfile if they exist
extra_gemfiles = [
  "#{__FILE__}.local",
  File.join(Dir.home, '.gemfile'),
]

extra_gemfiles.each do |gemfile|
  if File.file?(gemfile) && File.readable?(gemfile)
    eval(File.read(gemfile), binding)
  end
end
# vim: syntax=ruby
