---
CHANGELOG.md:
  delete: true
README.md:
  delete: true
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.travis.yml:
  delete: true

.gitignore:
  paths:
    - /CHANGELOG.md
    - /README.md
    - /appveyor.yml
    - /.gitlab-ci.yml
    - /.travis.yml
    - /update_report.txt
